all:
  children:
    kraken:
      children:
        kraken_server:
          hosts:
            KrakenMasterNode:
              ansible_host: 192.168.0.200
        kraken_agents:
          hosts:
            KrakenWorker1:
              ansible_host: 192.168.0.201
            KrakenWorker2:
              ansible_host: 192.168.0.202
            KrakenWorker3:
              ansible_host: 192.168.0.203
  vars:
    ansible_user: karl
    ansible_ssh_private_key_file: ~/.ssh/ansible
