ufw_allowed_ports:
  - { port: "22", proto: "tcp" }
  - { port: "80", proto: "tcp" }
  - { port: "2377", proto: "tcp" }
  - { port: "6443", proto: "tcp" }
  - { port: "7946", proto: "tcp" }
  - { port: "7946", proto: "udp" }
  - { port: "4789", proto: "udp" }
  - { port: "8472", proto: "udp" }
  - { port: "9001", proto: "tcp" }
  - { port: "9443", proto: "tcp" }
  - { port: "10250", proto: "tcp" }
